import {matchPerson,PresenceGate} from './presence-logic.js';
export async function setupPresence({gaze,say,busy,stopSpeech}){
 const d=window.desktop;if(!d)return;
 const panel=document.createElement('details');panel.id='presence-panel';panel.open=true;panel.innerHTML=`<summary>感知与视频对话</summary><label><input id="camera-enabled" type="checkbox">允许摄像头</label><video id="camera-preview" muted autoplay playsinline style="width:100%;max-height:180px;transform:scaleX(-1);background:#192522" hidden></video><label>视线<select id="gaze-mode"><option value="off">不跟随</option><option value="occasional" selected>偶尔看向我</option><option value="lock">一直看着我</option></select></label><p id="camera-state">摄像头未开启</p><label><input id="remember-enabled" type="checkbox">人物记忆与主动问候</label><p>人脸匹配只在本机进行，不保存视频。不确定或多人入镜时不认人。档案须本人同意。</p><input id="person-name" maxlength="40" placeholder="你的名字" style="width:100%"><label><input id="person-consent" type="checkbox">本人同意保存人脸特征与名字</label><button id="enroll-person">记住当前的人</button><div id="people-list"></div><label><input id="mic-enabled" type="checkbox">允许麦克风</label><label><input id="video-dialogue" type="checkbox">视频对话 · 唤醒词“凛”</label><p>唤醒后发送本次话语和一张当前画面给 Codex；不是连续视频流。人物档案不发送。</p><button id="listen-now">直接说一句</button><p id="mic-state">麦克风未开启</p><div id="transcript" style="white-space:pre-wrap"></div>`;
 const style=document.createElement('style');style.textContent='#presence-panel{margin:14px 0;padding:12px;border:1px solid #cbd7cd;border-radius:10px}#presence-panel label{display:flex;align-items:center;gap:8px;margin:10px 0}#presence-panel label select{flex:1;min-width:0}#presence-panel summary{font-weight:600;cursor:pointer}#people-list>div{display:flex;align-items:center;justify-content:space-between}';document.head.append(style);document.querySelector('aside').insertBefore(panel,document.getElementById('scene-settings'));
 const $=id=>document.getElementById(id),video=$('camera-preview');let stream=null,mic=null,context=null,processor=null,api=null,loop=null,generation=0,people=[],samples=[],singleSince=0,lastSeen=0,gate=new PresenceGate(),armedUntil=0,waiting=false,lastPartial='',resetAfterSpeech=false,micReady=false,micGeneration=0;
 function state(text){$('camera-state').textContent=text}
 async function loadModels(){if(api)return api;state('正在载入本地人脸模型…');const module=await import('../node_modules/@vladmandic/face-api/dist/face-api.esm.js');await module.tf.setBackend('webgl');await module.tf.ready();const base=new URL('../node_modules/@vladmandic/face-api/model',import.meta.url).href;await Promise.all([module.nets.tinyFaceDetector.loadFromUri(base),module.nets.faceLandmark68TinyNet.loadFromUri(base),module.nets.faceRecognitionNet.loadFromUri(base)]);api=module;return api}
 function zeroGaze(){gaze({x:0,y:0,active:false})}
 function stopCamera(){generation++;clearTimeout(loop);stream?.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null;video.hidden=true;samples=[];singleSince=0;zeroGaze();d.mediaPermission('video',false);state('摄像头已关闭');$('camera-enabled').checked=false;$('video-dialogue').checked=false}
 async function startCamera(){const token=++generation;await d.mediaPermission('video',true);try{const captured=await navigator.mediaDevices.getUserMedia({video:{width:640,height:480,frameRate:15},audio:false});if(token!==generation){captured.getTracks().forEach(t=>t.stop());return}stream=captured;video.srcObject=stream;video.hidden=false;await video.play();await loadModels();if(token===generation)detect(token)}catch(e){if(token!==generation)return;stopCamera();state('无法打开摄像头：'+e.message)}}
 async function detect(token){if(token!==generation||!stream)return;try{
  const faces=await api.detectAllFaces(video,new api.TinyFaceDetectorOptions({inputSize:224,scoreThreshold:.65})).withFaceLandmarks(true).withFaceDescriptors();if(token!==generation)return;const now=performance.now();
  if(faces.length===1&&faces[0].detection.score>.7){const f=faces[0],box=f.detection.box;lastSeen=now;if(!singleSince)singleSince=now;const x=1-2*(box.x+box.width/2)/video.videoWidth,y=1-2*(box.y+box.height/2)/video.videoHeight;const mode=$('gaze-mode').value,active=mode==='lock'||mode==='occasional'&&(now%11000<3300);gaze({x,y,active});samples.push(Array.from(f.descriptor));if(samples.length>6)samples.shift();
   if($('remember-enabled').checked){const result=matchPerson(Array.from(f.descriptor),people);state(result.kind==='known'?`面前可能是 ${result.person.name}`:result.kind==='unknown'?'看到了尚未登记的人':'暂时无法确认是谁');if(!busy()&&!$('video-dialogue').checked){const greeting=gate.update(result,now);if(greeting)say(greeting.text)}}else state('已检测到一张脸 · 本机跟踪中');
  }else{samples=[];singleSince=0;zeroGaze();gate.update({kind:'absent'},now);state(faces.length>1?'检测到多人，暂停认人和视线锁定':'等待你进入画面')}
 }catch(e){state('跟踪暂停：'+e.message);zeroGaze()}finally{if(token===generation)loop=setTimeout(()=>detect(token),250)}}
 $('camera-enabled').onchange=()=>{$('camera-enabled').checked?startCamera():stopCamera()};$('gaze-mode').onchange=()=>{if($('gaze-mode').value==='off')zeroGaze()};
 async function refreshPeople(){const r=await d.people();if(!r.ok){state(r.error);return}people=r.people;drawPeople()}
 function drawPeople(){$('people-list').replaceChildren();for(const p of people){const row=document.createElement('div'),label=document.createElement('span'),remove=document.createElement('button');label.textContent=p.name;remove.textContent='忘记';remove.onclick=async()=>{const r=await d.deletePerson(p.id);if(r.ok){people=r.people;drawPeople()}else state(r.error)};row.append(label,remove);$('people-list').append(row)}}
 $('enroll-person').onclick=async()=>{if(!stream||samples.length<3||performance.now()-singleSince<2000||performance.now()-lastSeen>1000){state('请让本人单独面对镜头，并保持两秒');return}if(!samples.every(s=>Math.hypot(...s.map((v,i)=>v-samples[0][i]))<.3)){state('画面有变化，请保持稳定后重试');return}const r=await d.savePerson({name:$('person-name').value,descriptors:samples.slice(-5),consent:$('person-consent').checked});if(r.ok){people=r.people;drawPeople();$('person-consent').checked=false;state('已在本机加密保存');say(`记住了，你叫${$('person-name').value}。`)}else state(r.error)};
 async function stopMic(){micGeneration++;micReady=false;processor?.disconnect();processor=null;mic?.getTracks().forEach(t=>t.stop());mic=null;if(context){await context.close();context=null}await d.stopListening();await d.mediaPermission('audio',false);$('mic-enabled').checked=false;$('video-dialogue').checked=false;$('mic-state').textContent='麦克风已关闭';armedUntil=0}
 async function startMic(){const token=++micGeneration;try{await d.mediaPermission('audio',true);const captured=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});if(token!==micGeneration){captured.getTracks().forEach(t=>t.stop());return}mic=captured;context=new AudioContext();await context.audioWorklet.addModule(new URL('./mic-worklet.js',import.meta.url));if(token!==micGeneration)return;processor=new AudioWorkletNode(context,'companion-capture');const source=context.createMediaStreamSource(mic),silent=context.createGain();silent.gain.value=0;source.connect(processor);processor.connect(silent);silent.connect(context.destination);const r=await d.startListening();if(!r.ok)throw Error(r.error);processor.port.onmessage=e=>{if(!micReady)return;if(busy()){resetAfterSpeech=true;return}if(resetAfterSpeech){d.micAudio({reset:true});resetAfterSpeech=false}d.micAudio(new Uint8Array(e.data))};$('mic-state').textContent='正在准备本地中文识别…'}catch(e){if(token!==micGeneration)return;await stopMic();$('mic-state').textContent='无法打开麦克风：'+e.message}}
 $('mic-enabled').onchange=()=>{$('mic-enabled').checked?startMic():stopMic()};
 $('video-dialogue').onchange=async()=>{if(!$('video-dialogue').checked){armedUntil=0;return}if(!stream){$('camera-enabled').checked=true;await startCamera()}if(!mic){$('mic-enabled').checked=true;await startMic()}if(stream&&mic){$('video-dialogue').checked=true;$('mic-state').textContent='说“凛”唤醒，再说你的问题。'}else $('video-dialogue').checked=false};
 $('listen-now').onclick=async()=>{stopSpeech();if(!mic){$('mic-enabled').checked=true;await startMic()}armedUntil=Date.now()+15000;d.micAudio({reset:true});$('mic-state').textContent='请说话，停顿后识别。'};
 async function submit(text){if(!text.trim()||waiting)return;$('transcript').textContent=text;const name=text.match(/(?:我叫|我的名字是)([^，。！？]{1,20})/);if(name)$('person-name').value=name[1];if(!$('video-dialogue').checked){document.getElementById('text').value=text;$('mic-state').textContent='已填入输入框，可以发送。';return}
  waiting=true;$('mic-state').textContent='已唤醒，正在发送话语和当前画面…';let image;
  if(stream&&video.readyState>=2){const canvas=document.createElement('canvas');canvas.width=640;canvas.height=Math.round(video.videoHeight/video.videoWidth*640);canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);const blob=await new Promise(r=>canvas.toBlob(r,'image/jpeg',.8));image=new Uint8Array(await blob.arrayBuffer())}
  try{const r=await d.videoSend({text,image});$('mic-state').textContent=r.ok?'Codex 正在看这张画面并回答…':r.error;if(!r.ok)waiting=false}catch(e){waiting=false;$('mic-state').textContent=e.message}
 }
 d.onMicText(e=>{if(e.type==='ready'){micReady=true;$('mic-state').textContent='麦克风已开启 · 本地识别';return}if(e.type==='error'){$('mic-state').textContent=e.message;return}if(busy()||waiting)return;if(e.type==='wake'&&$('video-dialogue').checked){armedUntil=Date.now()+15000;$('mic-state').textContent='我在听。';gaze({x:0,y:0,active:true});return}const text=e.text||'',wake=/^(?:你好)?[凛琳林临零]/;if($('video-dialogue').checked&&wake.test(text)){if(Date.now()>=armedUntil){armedUntil=Date.now()+15000;$('mic-state').textContent='我在听。';gaze({x:0,y:0,active:true})}}
  if(e.type==='partial'){if(Date.now()<armedUntil)$('transcript').textContent=text;return}if(e.type==='final'&&Date.now()<armedUntil){const content=text.replace(wake,'').replace(/^[，。\s]+/,'');if(content){armedUntil=0;submit(content)}}
 });
 d.onCodex(e=>{if(e.source==='panel'&&['answer','error','idle'].includes(e.state)){waiting=false;armedUntil=0;if(mic)$('mic-state').textContent='说“凛”开始下一次对话。'}});
 window.addEventListener('pagehide',()=>{stopCamera();stopMic()});await refreshPeople();
 window.companionPresence={getState:()=>({camera:!!stream,microphone:!!mic,people:people.length,ready:micReady}),loadModels,stopCamera,stopMic,video};
}
