const {_electron:electron}=require('playwright-core'),path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const profile=path.resolve('.runtime/v04-test');fs.mkdirSync(profile,{recursive:true});fs.writeFileSync(path.join(profile,'empty.jsonl'),'');const env={...process.env,RIN_PROFILE_DIR:profile,RIN_WATCH_FILE:path.join(profile,'empty.jsonl')};delete env.ELECTRON_RUN_AS_NODE;const app=await electron.launch({executablePath:require('electron'),args:[path.resolve('.')],env});
try{const page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.waitForFunction(()=>window.companionPreview?.animationsReady&&document.querySelector('#hologram-idleSeconds'),null,{timeout:120000});await page.waitForFunction(()=>window.companionExperience.hologram.progress===1);await page.locator('#autoblink').uncheck();await page.screenshot({path:'previews/v04-character.png'});
const voices=await page.evaluate(()=>window.desktop.voices());assert.ok(voices.voices.length>=18);
await page.locator('[data-tab="scene"]').click();await page.locator('#hologram-idleSeconds').fill('10');await page.waitForFunction(async()=>(await window.desktop.sceneSettings()).settings.hologram.idleSeconds===10);
await page.screenshot({path:'previews/v04-scene.png'});await page.evaluate(()=>{window.companionExperience.hologram.lastActivity=performance.now()-11000});await page.waitForFunction(()=>window.companionExperience.hologram.state==='hidden',null,{timeout:10000});await page.locator('#reveal').click();await page.waitForFunction(()=>window.companionExperience.hologram.progress>.35&&window.companionExperience.hologram.progress<.8);await page.screenshot({path:'previews/v04-hologram.png'});await page.waitForFunction(()=>window.companionExperience.hologram.state==='visible');
const gestures=await page.evaluate(()=>{const d=window.companionExperience.director;return ['Head','R_Upperarm','R_Forearm','R_Hand','Spine01'].map(n=>({name:n,present:d.bones.has('CC_Base_'+n)}))});assert.ok(gestures.every(g=>g.present));await page.locator('[data-tab="character"]').click();await page.locator('[data-gesture="wave"]').click();await page.waitForTimeout(1400);await page.screenshot({path:'previews/v04-wave.png'});
const result=await page.evaluate(()=>window.desktop.wallpaper(true));assert.ok(result.ok,result.error);const wallpaper=app.windows().find(p=>p.url().includes('mode=wallpaper'));await wallpaper.waitForFunction(()=>window.companionPreview?.animationsReady,null,{timeout:120000});const displays=(await page.evaluate(()=>window.desktop.sceneSettings())).displays,placements=[];
for(const display of displays){const r=await page.evaluate(async id=>{const r=await window.desktop.sceneSettings();return window.desktop.saveSceneSettings({...r.settings,displayId:id})},display.id);assert.ok(r.ok);const actual=JSON.parse(fs.readFileSync('desktop/runtime-status.json')).placement;const expected=await app.evaluate(({screen},id)=>screen.dipToScreenRect(null,screen.getAllDisplays().find(d=>d.id===id).bounds),display.id);for(const key of ['x','y','width','height'])assert.equal(actual[key],expected[key]);for(const [a,b] of [['clientX','x'],['clientY','y'],['clientWidth','width'],['clientHeight','height']])assert.equal(actual[a],expected[b],a);placements.push({actual,expected})}
await page.locator('[data-tab="voice"]').click();await page.screenshot({path:'previews/v04-voice.png'});const speech=await page.evaluate(()=>window.desktop.synthesize('你好，我是凛。我会在你需要的时候出现。','zh-CN-YunxiNeural',-5,2));assert.ok(speech.ok,speech.error);assert.ok(speech.timing.length);await page.evaluate(()=>window.desktop.publish({type:'activity',show:true}));await wallpaper.waitForFunction(()=>window.companionExperience.hologram.state==='visible');
await page.evaluate(()=>window.desktop.wallpaper(false));assert.deepEqual(errors,[]);fs.writeFileSync('test-results/v04.json',JSON.stringify({voices:voices.voices.length,hologramCycle:true,settingsSaved:true,gestures,placements,speechTiming:speech.timing.length,errors},null,2));console.log('v0.4 checks passed');
}finally{await app.close()}})().catch(e=>{console.error(e);process.exitCode=1});
